version: '2'
services:
  db_mysql:
   image: mysql:latest
   environment:
     MYSQL_ROOT_PASSWORD: rootpasswd
     MYSQL_DATABASE: webmail
     MYSQL_USER: webmail
     MYSQL_PASSWORD: webmailpasswd
   ports:
     - "3306:3306"
  mycomposer:
     build: .
  core:
   image: webdevops/php-nginx
   links:
     - mycomposer
     - db_mysql
   ports: 
     - "8080:80"
   volumes:
     - ./src:/app
     - ./src/vhost.conf:/opt/docker/etc/nginx/vhost.conf

